apiVersion: apps/v1
kind: Deployment
metadata:
  name: hercules-backend-service-deployment
spec:
  selector:
    matchLabels:
      app: hercules-backend-service
  replicas: 0
  template:
    metadata:
      labels:
        app: hercules-backend-service
        system: hercules
        lbtype: network-load-balancer
    spec:
      serviceAccountName: default-ksa
      nodeSelector:
        eks.amazonaws.com/capacityType: ON_DEMAND
      containers:
      - name: hercules-backend-service
        image: deployment-image
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 30Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 15
        envFrom:
        - configMapRef:
          name: hercules-backend-service-configs
        - secretRef:
          name: hercules-backend-service-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP