kind: Service
apiVersion: v1
metadata:
  name: chat-api-service
spec:
  type: NodePort
  selector:
    app: hercules-backend-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6382