apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hercules-main

resources:
- ../../base
- configmap.yml
- ingress.yml

images:
- name: deployment-image
  newName: hercules9/real-time-chat-app-frontend
  newTag: 4dfa65e0

replicas:
- count: 1
  name: hercules-frontend-service-deployment

patches:
- path: patch-deployment.yml
  target:
    kind: Deployment
