apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat-main

resources:
- ../../base
- configmap.yml
- ingress.yml

images:
- name: deployment-image
  newName: hercules9/my_image
  newTag: test_tag

replicas:
- count: 1
  name: hercules-frontend-service-deployment

patches:
- path: patch-deployment.yml
  target:
    kind: Deployment
