apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hercules-frontend-service-deployment
spec:
  template:
    spec:
      containers:
      - name: hercules-frontend-service
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 50Mi
      nodeSelector:
        eks.amazonaws.com/capacityType: ON_DEMAND