services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ALLOWED_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_WS_HOST=localhost
        - REACT_APP_WS_PORT=8080
        - REACT_APP_WS_PROTOCOL=ws
    container_name: chat-frontend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
