apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-resizable
provisioner: ebs.csi.aws.com
parameters: 
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - ap-southeast-1a
    - ap-southeast-1b