controller:
  nodeSelector: 
    eks.amazonaws.com/capacityType: ON_DEMAND
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      memory: 256Mi
node:
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      memory: 256Mi