apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat-main

resources:
- ../../base
- configmap.yml
- ingress.yml

images:
- name: deployment-image

replicas:
- count: 1
  name: hercules-backend-service-deployment

patches:
- path: patch-deployment.yml
  target:
    kind: Deployment
- path: patch-hpa.yml
  target:
    kind: HorizontalPodAutoscaler
