server:
  grpc_port: 50052
  http_port: 8082
  host: "0.0.0.0"

service:
  name: "user-service"
  version: "1.0.0"

clients:
  hello_service:
    host: "localhost"
    port: 50051
  auth_service:
    host: "localhost"
    port: 50053

database:
  type: "memory"  # In-memory storage for demo

logging:
  level: "info"
  format: "json"
