name: App Backend Deployment

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'app/backend/**'

jobs:
  cd:
    name: Run
    uses: ./.github/workflows/cd.yml
    with:
      registry: real-time-chat-app-backend
      environment: "eks-${{ github.ref_name }}"
    permissions:
      contents: write
    secrets: inherit
